server:
  port: ":8080"
  secret_key: "communist_revolution_secret_2027"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "unitycn"
  sslmode: "disable"

admin:
  username: "admin"
  password: "$2b$10$xr4.dNv7AKDVs3ptGiq8LOui1lZ2SWR7zQwHjs1QzG7uX9sxubus." 